aiven/aiven-examples

- mysql/python/README.md
- mysql/python/main.py
- tests/test_aiven_examples.py
Adding a basic example + test for MySQL (only python in this PR).
> mysql: add simple python example

- m3/python/main.py
Handle another possible expected message when creating a service integration that already exists.
> m3: handle service integration errors

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/report.md
- .github/ISSUE_TEMPLATE/request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This adds:
* templates for pull requests
* a selection of templates for issues (question/bug/request)
* the Aiven Code of Conduct
* a simple and friendly contributing file
> Improve community-facing files

- README.rst
- opensearch/python/README.md
- opensearch/python/main.py
Create folder for OpenSearch and add an example because soon we will not support ElasticsSearch
Signed-off-by: laysa.uchoa <laysa.uchoa@aiven.io>
> Add Python OpenSearch example

- README.rst
Add disclaimer and full name for Apache projects.
> Update README to comply with trademarks

- README.rst
Add more products in trademark disclaimer
> Add products in disclaimer

- README.rst
Update disclaimer for Redis and add proper TM and R symbols.
> Update disclaimer for Redis

- solutions/README.rst
- solutions/node-replacement-monitoring/Dockerfile
- solutions/node-replacement-monitoring/README.md
- solutions/node-replacement-monitoring/node_monitor.sh
Adds a script that monitors node replacements and pushes metrics to an InfluxDB service
> Add node monitoring script

- solutions/scripts/avn-pgdump.sh
- solutions/scripts/avn-redisfork.sh
- solutions/scripts/service-ipwatch.sh
miscellaneous scripts using avn cli for avn services
> Fwu scripts

- solutions/kafka-schema-registry/README.md
mainly to avoid confushion on mixing up passwords
> Updated instructions for avro example

- solutions/scripts/avn-shutoff-services.sh
Simple script to shut down all services for a given project. 
Relies on JQ
> script to shut down all services in a project

- solutions/pg-kafka-bigquery/.gitignore
- solutions/pg-kafka-bigquery/README.md
- solutions/pg-kafka-bigquery/bigquery-sink.json.template
- solutions/pg-kafka-bigquery/consume.py
- solutions/pg-kafka-bigquery/debezium-pgsql.json.template
- solutions/pg-kafka-bigquery/produce.py
- solutions/pg-kafka-bigquery/requirements.txt
Add a new sample solution:
PostgreSQL => Debezium CDC => Kafka => BigQuery
> solutions: Sample code with Debezium and BigQuery

- solutions/pg-sync/config/test.json
- solutions/pg-sync/src/avro_main.py
- solutions/pg-sync/src/env.py
- solutions/pg-sync/src/pg_data_writer.py
- solutions/pg-sync/src/utilities.py
- solutions/pg-sync/terraform/main.tf
> merge pg-sync avro support

- .github/ISSUE_TEMPLATE/request.md
- README.rst
- redis/go/README.md
- redis/nodejs/README.md
- redis/python/README.md
- terraform/README.md
> updated Redis to Redis®

- solutions/tf-aiven-stack/.gitignore
- solutions/tf-aiven-stack/README.md
- solutions/tf-aiven-stack/main.tf
- solutions/tf-aiven-stack/modules/metrics-logs/main.tf
- solutions/tf-aiven-stack/modules/metrics-logs/variables.tf
- solutions/tf-aiven-stack/modules/stack/main.tf
- solutions/tf-aiven-stack/modules/stack/variables.tf
- solutions/tf-aiven-stack/variables.tf
Adding example of deploying kafka and opensearch services as a module with metrics, logs and prometheus endpoint integrations
> adding TF application stack example

- kafka/python/README.md
Wrapped the examples to make them easier to read
> Format example commands

- solutions/scripts/aiven-clickhouse-client.sh
Script to simplify connecting to and loading data into ClickHouse from the command line
> adding utility script to query and load data to Aiven for ClickHouse

- solutions/scripts/avn-fork-mysqldump.sh
A script that creates 
- a fork of a primary mysql instance, 
- creates a mysqldump to download and then terminate the fork once the dump is accomplished.
> MySQL Fork and mysqldump utility for secondary backup download

- kafka/kafka-streams/README.md
- kafka/kafka-streams/build.sh
- kafka/kafka-streams/src/KafkaMusicExample.java
- kafka/kafka-streams/src/KafkaMusicExampleDriver.java
- kafka/kafka-streams/terraform/avn-token.sh
- kafka/kafka-streams/terraform/data.tf
- kafka/kafka-streams/terraform/provider.tf
- kafka/kafka-streams/terraform/services.tf
- kafka/kafka-streams/terraform/variables.tf
automate Kafka Streams example
https://docs.aiven.io/docs/products/kafka/howto/kafka-streams-with-aiven-for-kafka.html
> Kafka Streams example

- kafka/kafka-streams/makeconf.sh
> add missing makeconf.sh for kafka-streams example

- terraform/mysql/README.rst
- terraform/mysql/mysql-datadog.tf
- terraform/mysql/provider.tf
- terraform/mysql/variables.tf
> terraform example - mysql and datadog integration

- solutions/scripts/avn-dns-probe.sh
this script probes DNS to detect aiven nodes replacements.
> avn-dns-probe.sh to monitor dns changes

- solutions/scripts/avn-invoice-csv.sh
- solutions/scripts/avn-invoice-pdf.sh
scripts to generate CSV and PDF invoices from a project by avn API
> added scripts to generate csv and pdf invoices from a project

- solutions/kafka-client-aes/.gitignore
- solutions/kafka-client-aes/README.md
- solutions/kafka-client-aes/aes_consumer.py
- solutions/kafka-client-aes/aes_producer.py
- solutions/kafka-client-aes/requirements.txt
> add kafka custom serde example

- terraform/pg/pg-fork/provider.tf
- terraform/pg/pg-fork/readme.rst
- terraform/pg/pg-fork/service.tf
- terraform/pg/pg-fork/variables.tf
> Terraform script for pg-fork

- solutions/scripts/avn-dns-probe.sh
- solutions/scripts/dd-custom-metric.sh
example on sending custom metrics on events such as node recycle in aiven.
> add dd-custom-metric script

- solutions/pg2ch/README.md
- solutions/pg2ch/pg2ch.env
- solutions/pg2ch/pg2ch.sh
- solutions/pg2ch/table_sizes.sql
pg2ch - migrate postgresql tables to clickhouse
> pg2ch - migrate postgresql tables to clickhouse

- opensearch/opensearch-kafka/readme.md
- opensearch/opensearch-kafka/terraform/variables.tf
documentation & minor bug fix.  Removed unnecessary variable at apply command
> minor fixes

- solutions/temporalio/README.md
> Fix temporal config

- solutions/autoscaling/autoscale.sh
> fixed hardcoded DNS for autoscaling demo

- kafka/cc/.gitignore
- kafka/cc/CMakeLists.txt
- kafka/cc/README.md
- kafka/cc/avn_KafkaConsumer_Simple.cc
- kafka/cc/avn_KafkaProducer_Simple.cc
- kafka/cc/ccexample.env
- kafka/cc/ccexample.sh
- kafka/cc/config.hh
Kafka Modern C++ Example uses modern-cpp-kafka
> Kafka Modern C++ Example

- solutions/scripts/kafka-collector.sh
> Kafka collector script to gather Kafka cluster configuration details

- solutions/flink-kafka/README.md
- solutions/flink-kafka/lab.sh
- solutions/flink-kafka/terraform/stockdata.tf
- solutions/flink-kafka/terraform/variables.tf
> flink stock demo - terraform updates

- solutions/clickhouse-cdc/.gitignore
- solutions/clickhouse-cdc/README.md
- solutions/clickhouse-cdc/ch_drop.sql
- solutions/clickhouse-cdc/ch_users.sql
- solutions/clickhouse-cdc/kcat.config.template
- solutions/clickhouse-cdc/lab.env
- solutions/clickhouse-cdc/lab.sh
- solutions/clickhouse-cdc/mv.sql.template
- solutions/clickhouse-cdc/pg_tables.sql
- solutions/clickhouse-cdc/terraform/avn-token.sh
- solutions/clickhouse-cdc/terraform/cdc.tf
- solutions/clickhouse-cdc/terraform/data.tf
- solutions/clickhouse-cdc/terraform/provider.tf
- solutions/clickhouse-cdc/terraform/variables.tf
> ClickHouse CDC MV demo [ pg -> kafka -> ch ]

- solutions/clickhouse-dbt/README.md
- solutions/clickhouse-dbt/actor_summary.sql
- solutions/clickhouse-dbt/ch-dbt.env
- solutions/clickhouse-dbt/ch-dbt.sh
- solutions/clickhouse-dbt/create.sql
- solutions/clickhouse-dbt/dbt_project.yml.sample
- solutions/clickhouse-dbt/insert.sql
- solutions/clickhouse-dbt/profiles.yml.sample
- solutions/clickhouse-dbt/requirements.txt
- solutions/clickhouse-dbt/schema.yml
- solutions/clickhouse-dbt/select-imdb_dbt.sql
- solutions/clickhouse-dbt/select.sql
This demostrates how to integrate dbt with clickhouse and run a Simple View Materialization demo.
> clickhouse dbt demo

- solutions/clickhouse-cdc/README.md
- solutions/clickhouse-cdc/lab.env
- solutions/clickhouse-cdc/lab.sh
- solutions/clickhouse-cdc/terraform/cdc.tf
- fixed sed options to be compatible for cross platform
- added "topic.prefix" = "middleearth-replicator" - new required config for connector config
- added better TF dependencies to avoid racing conditions on resource creation which causes connector to fail
> clickhouse cdc dependencies timing + script fixes

- solutions/reapply-ism-policies/README.md
- solutions/reapply-ism-policies/avn-re-apply-ism-policies.py
- solutions/reapply-ism-policies/sample.conf
> Initial version of reapplying opendistro ism policies to opensearch

- solutions/migrate-opendistro-security-to-aiven-for-opensearch/avn-migrate-os-security-config.py
- solutions/reapply-ism-policies/README.md
- solutions/reapply-ism-policies/avn-re-apply-ism-policies.py
- add better error messages to ism migration
- add option to run ism migration multiple times
- print number of security configuration changes performed by the security migration script
> Improve ISM and security config migration scripts.

- solutions/validate-elasticsearch-to-opensearch-migration/compare_migration_validation_data.py
- solutions/validate-elasticsearch-to-opensearch-migration/elasticsearch_client.py
- solutions/validate-elasticsearch-to-opensearch-migration/get_migration_validation_data.py
- solutions/validate-elasticsearch-to-opensearch-migration/pre_snapshot_checks.py
> Tooling to validate ES to OS migration

- solutions/kafka-connect-secret-provider/README.md
- solutions/kafka-connect-secret-provider/avn-token.sh
- solutions/kafka-connect-secret-provider/data.tf
- solutions/kafka-connect-secret-provider/insert_samples.sh
- solutions/kafka-connect-secret-provider/main.tf
- solutions/kafka-connect-secret-provider/provider.tf
- solutions/kafka-connect-secret-provider/publication.sql
- solutions/kafka-connect-secret-provider/read_topic.sh
- solutions/kafka-connect-secret-provider/variables.tf
Demo on how to use the secret-provider for Kafka Connect
> Add kafka connect secret-provider example

- solutions/tf-stack-o11y/modules/metrics-logs/main.tf
- solutions/tf-stack-o11y/modules/metrics-logs/provider.tf
- solutions/tf-stack-o11y/modules/metrics-logs/variables.tf
> Observability Terraform Stack

- solutions/clickhouse-tf-stack/main.tf
- solutions/clickhouse-tf-stack/provider.tf
- solutions/clickhouse-tf-stack/variables.tf
> Initial CH setup stack

- solutions/mysql-tf-stack-demo/main.tf
- solutions/mysql-tf-stack-demo/provider.tf
- solutions/mysql-tf-stack-demo/variables.tf
- solutions/tf-stack-o11y/modules/metrics-logs/main.tf
- solutions/tf-stack-o11y/modules/metrics-logs/provider.tf
- solutions/tf-stack-o11y/modules/metrics-logs/variables.tf
MySQL TF stack and O11y Stack Updates with Thanos inclusion
> MySQL TF stack and O11y Stack Updates with Thanos inclusion
